name: CI
on: [workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build-apk:
    runs-on: ubuntu-latest
    name: Build APK
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
      - run: flutter --version
      - name: Install Dependencies
        run: flutter pub get
      - name: Build
        run: flutter build apk --release
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ApkReleases
          path: build/app/outputs/flutter-apk/app-release.apk
  build-windows:
    runs-on: windows-latest
    name: Build Windows
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
      - run: flutter --version
      - name: Install Dependencies
        run: flutter pub get
      - name: Build
        run: flutter build windows
      - name: package
        run: |
          cd build
          tar -czvf windows-build.tgz windows/x64/runner/Release
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: WindowsRelease
          path: build/windows-build.tgz
  build-web:
    runs-on: ubuntu-latest
    name: Build Web
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
      - run: flutter --version
      - name: Install Dependencies
        run: flutter pub get
      - name: Build
        run: flutter build web --base-href=/getsomepuzzle/
      - name: package
        run: |
          cd build
          tar -czvf web-build.tgz web
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: WebRelease
          path: build/web-build.tgz
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build-apk, build-windows, build-web]
    steps:
    - name: Extract version from pubspec.yaml
      id: extract_version
      run: |
        version=$(grep '^version: ' pubspec.yaml | cut -d ' ' -f 2 | tr -d '\r')
        echo "VERSION=$version" >> $GITHUB_ENV
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/app/outputs/flutter-apk/app-release.apk,build/windows-build.tgz,build/web-build.tgz"
        name: v${{ env.VERSION }}
